//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgPaymentService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.GeneralCrmObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.BaseBillableObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.PaymentInfo))]
    public partial class BaseCrmObjectInfo : object
    {
        
        private System.DateTime CreatDateField;
        
        private System.Nullable<System.Guid> CrmIdField;
        
        private string CrmObjectTypeCodeField;
        
        private System.Guid CrmObjectTypeIdField;
        
        private int CrmObjectTypeIndexField;
        
        private string CrmObjectTypeNameField;
        
        private PgPaymentService.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        private System.DateTime ModifyDateField;
        
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        private System.Nullable<int> ProcessStateIndexField;
        
        private string RefIdField;
        
        private string StageField;
        
        private System.Nullable<System.Guid> StageIdField;
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate
        {
            get
            {
                return this.CreatDateField;
            }
            set
            {
                this.CreatDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode
        {
            get
            {
                return this.CrmObjectTypeCodeField;
            }
            set
            {
                this.CrmObjectTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmObjectTypeId
        {
            get
            {
                return this.CrmObjectTypeIdField;
            }
            set
            {
                this.CrmObjectTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex
        {
            get
            {
                return this.CrmObjectTypeIndexField;
            }
            set
            {
                this.CrmObjectTypeIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName
        {
            get
            {
                return this.CrmObjectTypeNameField;
            }
            set
            {
                this.CrmObjectTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgPaymentService.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties
        {
            get
            {
                return this.ExtendedPropertiesField;
            }
            set
            {
                this.ExtendedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId
        {
            get
            {
                return this.ParentCrmObjectIdField;
            }
            set
            {
                this.ParentCrmObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProcessStateIndex
        {
            get
            {
                return this.ProcessStateIndexField;
            }
            set
            {
                this.ProcessStateIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stage
        {
            get
            {
                return this.StageField;
            }
            set
            {
                this.StageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.StageIdField;
            }
            set
            {
                this.StageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.BaseBillableObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.PaymentInfo))]
    public partial class GeneralCrmObjectInfo : PgPaymentService.BaseCrmObjectInfo
    {
        
        private string DescriptionField;
        
        private System.Nullable<System.Guid> IdentityIdField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBillableObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.PaymentInfo))]
    public partial class BaseBillableObjectInfo : PgPaymentService.GeneralCrmObjectInfo
    {
        
        private string BillableObjectStateField;
        
        private decimal FinalValueField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillableObjectState
        {
            get
            {
                return this.BillableObjectStateField;
            }
            set
            {
                this.BillableObjectStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FinalValue
        {
            get
            {
                return this.FinalValueField;
            }
            set
            {
                this.FinalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PaymentInfo : PgPaymentService.BaseBillableObjectInfo
    {
        
        private string BranchCodeField;
        
        private string ChequeBankField;
        
        private string ChequeNoField;
        
        private string CrmPaymentTypeField;
        
        private System.Nullable<bool> IsPayedField;
        
        private string MoneyAccountField;
        
        private System.Nullable<System.DateTime> PayDateField;
        
        private string PaymentMethodField;
        
        private string PaymentTypeField;
        
        private string ReceiptCardNoField;
        
        private string RefNoField;
        
        private PgPaymentService.RelatedInvoiceInfo RelatedInvoiceNumberField;
        
        private System.Nullable<System.DateTime> SettledDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeBank
        {
            get
            {
                return this.ChequeBankField;
            }
            set
            {
                this.ChequeBankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeNo
        {
            get
            {
                return this.ChequeNoField;
            }
            set
            {
                this.ChequeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmPaymentType
        {
            get
            {
                return this.CrmPaymentTypeField;
            }
            set
            {
                this.CrmPaymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPayed
        {
            get
            {
                return this.IsPayedField;
            }
            set
            {
                this.IsPayedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoneyAccount
        {
            get
            {
                return this.MoneyAccountField;
            }
            set
            {
                this.MoneyAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PayDate
        {
            get
            {
                return this.PayDateField;
            }
            set
            {
                this.PayDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentType
        {
            get
            {
                return this.PaymentTypeField;
            }
            set
            {
                this.PaymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptCardNo
        {
            get
            {
                return this.ReceiptCardNoField;
            }
            set
            {
                this.ReceiptCardNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgPaymentService.RelatedInvoiceInfo RelatedInvoiceNumber
        {
            get
            {
                return this.RelatedInvoiceNumberField;
            }
            set
            {
                this.RelatedInvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SettledDate
        {
            get
            {
                return this.SettledDateField;
            }
            set
            {
                this.SettledDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class BaseCrmObjectExtendedPropertyInfo : object
    {
        
        private string NameField;
        
        private string UserKeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedInvoiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class RelatedInvoiceInfo : object
    {
        
        private System.Nullable<System.Guid> RelatedInvoiceIdField;
        
        private string RelatedInvoiceNumberField;
        
        private string RelatedInvoiceTypeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> RelatedInvoiceId
        {
            get
            {
                return this.RelatedInvoiceIdField;
            }
            set
            {
                this.RelatedInvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedInvoiceNumber
        {
            get
            {
                return this.RelatedInvoiceNumberField;
            }
            set
            {
                this.RelatedInvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedInvoiceTypeCode
        {
            get
            {
                return this.RelatedInvoiceTypeCodeField;
            }
            set
            {
                this.RelatedInvoiceTypeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.PaymentInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgPaymentService.SaveCrmObjectResult))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PaymentInfoResult : PgPaymentService.OperationResult
    {
        
        private PgPaymentService.PaymentInfo PaymentInfoField;
        
        private PgPaymentService.PaymentInfo[] PaymentInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgPaymentService.PaymentInfo PaymentInfo
        {
            get
            {
                return this.PaymentInfoField;
            }
            set
            {
                this.PaymentInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgPaymentService.PaymentInfo[] PaymentInfoList
        {
            get
            {
                return this.PaymentInfoListField;
            }
            set
            {
                this.PaymentInfoListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class SaveCrmObjectResult : PgPaymentService.OperationResult
    {
        
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.Domain.Model")]
    public enum CrmObjectDeleteOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgPaymentService.IPayment")]
    public interface IPayment
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/SavePayment", ReplyAction="http://tempuri.org/IPayment/SavePaymentResponse")]
        PgPaymentService.SaveCrmObjectResult SavePayment(string userName, string password, PgPaymentService.PaymentInfo paymentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/SavePayment", ReplyAction="http://tempuri.org/IPayment/SavePaymentResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> SavePaymentAsync(string userName, string password, PgPaymentService.PaymentInfo paymentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/DeletePaymentById", ReplyAction="http://tempuri.org/IPayment/DeletePaymentByIdResponse")]
        PgPaymentService.SaveCrmObjectResult DeletePaymentById(string userName, string password, System.Guid crmId, PgPaymentService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/DeletePaymentById", ReplyAction="http://tempuri.org/IPayment/DeletePaymentByIdResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> DeletePaymentByIdAsync(string userName, string password, System.Guid crmId, PgPaymentService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/DeletePaymentByNumber", ReplyAction="http://tempuri.org/IPayment/DeletePaymentByNumberResponse")]
        PgPaymentService.SaveCrmObjectResult DeletePaymentByNumber(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/DeletePaymentByNumber", ReplyAction="http://tempuri.org/IPayment/DeletePaymentByNumberResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> DeletePaymentByNumberAsync(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindPaymentByNumber", ReplyAction="http://tempuri.org/IPayment/FindPaymentByNumberResponse")]
        PgPaymentService.PaymentInfoResult FindPaymentByNumber(string userName, string password, string number, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindPaymentByNumber", ReplyAction="http://tempuri.org/IPayment/FindPaymentByNumberResponse")]
        System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindPaymentByNumberAsync(string userName, string password, string number, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/DeleteReceiptByNumber", ReplyAction="http://tempuri.org/IPayment/DeleteReceiptByNumberResponse")]
        PgPaymentService.SaveCrmObjectResult DeleteReceiptByNumber(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/DeleteReceiptByNumber", ReplyAction="http://tempuri.org/IPayment/DeleteReceiptByNumberResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> DeleteReceiptByNumberAsync(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindReceiptByNumber", ReplyAction="http://tempuri.org/IPayment/FindReceiptByNumberResponse")]
        PgPaymentService.PaymentInfoResult FindReceiptByNumber(string userName, string password, string number, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindReceiptByNumber", ReplyAction="http://tempuri.org/IPayment/FindReceiptByNumberResponse")]
        System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindReceiptByNumberAsync(string userName, string password, string number, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/SearchPayment", ReplyAction="http://tempuri.org/IPayment/SearchPaymentResponse")]
        PgPaymentService.PaymentInfoResult SearchPayment(string userName, string password, string query, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/SearchPayment", ReplyAction="http://tempuri.org/IPayment/SearchPaymentResponse")]
        System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> SearchPaymentAsync(string userName, string password, string query, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/SearchReceipt", ReplyAction="http://tempuri.org/IPayment/SearchReceiptResponse")]
        PgPaymentService.PaymentInfoResult SearchReceipt(string userName, string password, string query, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/SearchReceipt", ReplyAction="http://tempuri.org/IPayment/SearchReceiptResponse")]
        System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> SearchReceiptAsync(string userName, string password, string query, string crmObjectTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindPaymentById", ReplyAction="http://tempuri.org/IPayment/FindPaymentByIdResponse")]
        PgPaymentService.PaymentInfoResult FindPaymentById(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindPaymentById", ReplyAction="http://tempuri.org/IPayment/FindPaymentByIdResponse")]
        System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindPaymentByIdAsync(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindReceiptById", ReplyAction="http://tempuri.org/IPayment/FindReceiptByIdResponse")]
        PgPaymentService.PaymentInfoResult FindReceiptById(string userName, string password, System.Guid receiptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/FindReceiptById", ReplyAction="http://tempuri.org/IPayment/FindReceiptByIdResponse")]
        System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindReceiptByIdAsync(string userName, string password, System.Guid receiptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/ApprovedPayment", ReplyAction="http://tempuri.org/IPayment/ApprovedPaymentResponse")]
        PgPaymentService.SaveCrmObjectResult ApprovedPayment(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/ApprovedPayment", ReplyAction="http://tempuri.org/IPayment/ApprovedPaymentResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> ApprovedPaymentAsync(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/RejectedPayment", ReplyAction="http://tempuri.org/IPayment/RejectedPaymentResponse")]
        PgPaymentService.SaveCrmObjectResult RejectedPayment(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/RejectedPayment", ReplyAction="http://tempuri.org/IPayment/RejectedPaymentResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> RejectedPaymentAsync(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/PendingPayment", ReplyAction="http://tempuri.org/IPayment/PendingPaymentResponse")]
        PgPaymentService.SaveCrmObjectResult PendingPayment(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/PendingPayment", ReplyAction="http://tempuri.org/IPayment/PendingPaymentResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> PendingPaymentAsync(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/NumberedPayment", ReplyAction="http://tempuri.org/IPayment/NumberedPaymentResponse")]
        PgPaymentService.SaveCrmObjectResult NumberedPayment(string userName, string password, System.Guid paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayment/NumberedPayment", ReplyAction="http://tempuri.org/IPayment/NumberedPaymentResponse")]
        System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> NumberedPaymentAsync(string userName, string password, System.Guid paymentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IPaymentChannel : PgPaymentService.IPayment, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PaymentClient : System.ServiceModel.ClientBase<PgPaymentService.IPayment>, PgPaymentService.IPayment
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaymentClient() : 
                base(PaymentClient.GetDefaultBinding(), PaymentClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPayment.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentClient(EndpointConfiguration endpointConfiguration) : 
                base(PaymentClient.GetBindingForEndpoint(endpointConfiguration), PaymentClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaymentClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaymentClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgPaymentService.SaveCrmObjectResult SavePayment(string userName, string password, PgPaymentService.PaymentInfo paymentInfo)
        {
            return base.Channel.SavePayment(userName, password, paymentInfo);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> SavePaymentAsync(string userName, string password, PgPaymentService.PaymentInfo paymentInfo)
        {
            return base.Channel.SavePaymentAsync(userName, password, paymentInfo);
        }
        
        public PgPaymentService.SaveCrmObjectResult DeletePaymentById(string userName, string password, System.Guid crmId, PgPaymentService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeletePaymentById(userName, password, crmId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> DeletePaymentByIdAsync(string userName, string password, System.Guid crmId, PgPaymentService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeletePaymentByIdAsync(userName, password, crmId, deleteOption);
        }
        
        public PgPaymentService.SaveCrmObjectResult DeletePaymentByNumber(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeletePaymentByNumber(userName, password, number, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> DeletePaymentByNumberAsync(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeletePaymentByNumberAsync(userName, password, number, deleteOption);
        }
        
        public PgPaymentService.PaymentInfoResult FindPaymentByNumber(string userName, string password, string number, string crmObjectTypeCode)
        {
            return base.Channel.FindPaymentByNumber(userName, password, number, crmObjectTypeCode);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindPaymentByNumberAsync(string userName, string password, string number, string crmObjectTypeCode)
        {
            return base.Channel.FindPaymentByNumberAsync(userName, password, number, crmObjectTypeCode);
        }
        
        public PgPaymentService.SaveCrmObjectResult DeleteReceiptByNumber(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteReceiptByNumber(userName, password, number, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> DeleteReceiptByNumberAsync(string userName, string password, string number, PgPaymentService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteReceiptByNumberAsync(userName, password, number, deleteOption);
        }
        
        public PgPaymentService.PaymentInfoResult FindReceiptByNumber(string userName, string password, string number, string crmObjectTypeCode)
        {
            return base.Channel.FindReceiptByNumber(userName, password, number, crmObjectTypeCode);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindReceiptByNumberAsync(string userName, string password, string number, string crmObjectTypeCode)
        {
            return base.Channel.FindReceiptByNumberAsync(userName, password, number, crmObjectTypeCode);
        }
        
        public PgPaymentService.PaymentInfoResult SearchPayment(string userName, string password, string query, string crmObjectTypeCode)
        {
            return base.Channel.SearchPayment(userName, password, query, crmObjectTypeCode);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> SearchPaymentAsync(string userName, string password, string query, string crmObjectTypeCode)
        {
            return base.Channel.SearchPaymentAsync(userName, password, query, crmObjectTypeCode);
        }
        
        public PgPaymentService.PaymentInfoResult SearchReceipt(string userName, string password, string query, string crmObjectTypeCode)
        {
            return base.Channel.SearchReceipt(userName, password, query, crmObjectTypeCode);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> SearchReceiptAsync(string userName, string password, string query, string crmObjectTypeCode)
        {
            return base.Channel.SearchReceiptAsync(userName, password, query, crmObjectTypeCode);
        }
        
        public PgPaymentService.PaymentInfoResult FindPaymentById(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.FindPaymentById(userName, password, paymentId);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindPaymentByIdAsync(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.FindPaymentByIdAsync(userName, password, paymentId);
        }
        
        public PgPaymentService.PaymentInfoResult FindReceiptById(string userName, string password, System.Guid receiptId)
        {
            return base.Channel.FindReceiptById(userName, password, receiptId);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.PaymentInfoResult> FindReceiptByIdAsync(string userName, string password, System.Guid receiptId)
        {
            return base.Channel.FindReceiptByIdAsync(userName, password, receiptId);
        }
        
        public PgPaymentService.SaveCrmObjectResult ApprovedPayment(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.ApprovedPayment(userName, password, paymentId);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> ApprovedPaymentAsync(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.ApprovedPaymentAsync(userName, password, paymentId);
        }
        
        public PgPaymentService.SaveCrmObjectResult RejectedPayment(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.RejectedPayment(userName, password, paymentId);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> RejectedPaymentAsync(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.RejectedPaymentAsync(userName, password, paymentId);
        }
        
        public PgPaymentService.SaveCrmObjectResult PendingPayment(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.PendingPayment(userName, password, paymentId);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> PendingPaymentAsync(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.PendingPaymentAsync(userName, password, paymentId);
        }
        
        public PgPaymentService.SaveCrmObjectResult NumberedPayment(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.NumberedPayment(userName, password, paymentId);
        }
        
        public System.Threading.Tasks.Task<PgPaymentService.SaveCrmObjectResult> NumberedPaymentAsync(string userName, string password, System.Guid paymentId)
        {
            return base.Channel.NumberedPaymentAsync(userName, password, paymentId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPayment))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPayment))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/IPayment.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaymentClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPayment);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaymentClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPayment);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPayment,
        }
    }
}
